<?xml version="1.0" encoding="utf-8"?><Database Name="SICAP-2014" Class="CapaDatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JORGE-TORRES-PC\SQL2012;Initial Catalog=SICAP-2014;Integrated Security=True" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="SICAP_2014ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FaltasPersonalporMeses" Member="FaltasPersonalporMeses">
    <Type Name="FaltasPersonalporMeses">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalporAsistencia" Member="PersonalporAsistencia">
    <Type Name="PersonalporAsistencia">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="HoraEntrada" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="HoraSalida" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Tiempo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDASISTENCIA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalporFaltaDia" Member="PersonalporFaltaDia">
    <Type Name="PersonalporFaltaDia">
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VistaReporteUsers" Member="VistaReporteUsers">
    <Type Name="VistaReporteUsers">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ROL" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="NICK" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VistaUsuarios" Member="VistaUsuarios">
    <Type Name="VistaUsuarios">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ROL" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_USUARIO" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ASISTENCIA" Member="ASISTENCIA">
    <Type Name="ASISTENCIA">
      <Column Name="IDASISTENCIA" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DETALLE_PERSONAL_CALENDARIO_ASISTENCIA" Member="DETALLE_PERSONAL_CALENDARIO" ThisKey="IDCALENDARIO,CEDULA" OtherKey="IDCALENDARIO,CEDULA" Type="DETALLE_PERSONAL_CALENDARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AYUDA" Member="AYUDA">
    <Type Name="AYUDA">
      <Column Name="IDAYUDA" Type="System.Decimal" DbType="Decimal(9,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="DATAARCHIVO" Type="System.Data.Linq.Binary" DbType="VarBinary(8000) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CALENDARIO" Member="CALENDARIO">
    <Type Name="CALENDARIO">
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FECHAINICIO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAFIN" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CALENDARIO_DETALLE_PERSONAL_CALENDARIO" Member="DETALLE_PERSONAL_CALENDARIO" ThisKey="IDCALENDARIO" OtherKey="IDCALENDARIO" Type="DETALLE_PERSONAL_CALENDARIO" />
      <Association Name="CALENDARIO_DIASADICIONALES" Member="DIASADICIONALES" ThisKey="IDCALENDARIO" OtherKey="IDCALENDARIO" Type="DIASADICIONALES" />
      <Association Name="CALENDARIO_DIASNOLABORABLES" Member="DIASNOLABORABLES" ThisKey="IDCALENDARIO" OtherKey="IDCALENDARIO" Type="DIASNOLABORABLES" />
    </Type>
  </Table>
  <Table Name="dbo.DETALLE_IMPREVISTO_CALENDARIO" Member="DETALLE_IMPREVISTO_CALENDARIO">
    <Type Name="DETALLE_IMPREVISTO_CALENDARIO">
      <Column Name="IDIMPREVISTO" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DETALLE_PERSONAL_CALENDARIO_DETALLE_IMPREVISTO_CALENDARIO" Member="DETALLE_PERSONAL_CALENDARIO" ThisKey="IDCALENDARIO,CEDULA" OtherKey="IDCALENDARIO,CEDULA" Type="DETALLE_PERSONAL_CALENDARIO" IsForeignKey="true" />
      <Association Name="IMPREVISTOS_DETALLE_IMPREVISTO_CALENDARIO" Member="IMPREVISTOS" ThisKey="IDIMPREVISTO" OtherKey="IDIMPREVISTO" Type="IMPREVISTOS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DETALLE_PERSONAL_CALENDARIO" Member="DETALLE_PERSONAL_CALENDARIO">
    <Type Name="DETALLE_PERSONAL_CALENDARIO">
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DETALLE_PERSONAL_CALENDARIO_ASISTENCIA" Member="ASISTENCIA" ThisKey="IDCALENDARIO,CEDULA" OtherKey="IDCALENDARIO,CEDULA" Type="ASISTENCIA" />
      <Association Name="DETALLE_PERSONAL_CALENDARIO_DETALLE_IMPREVISTO_CALENDARIO" Member="DETALLE_IMPREVISTO_CALENDARIO" ThisKey="IDCALENDARIO,CEDULA" OtherKey="IDCALENDARIO,CEDULA" Type="DETALLE_IMPREVISTO_CALENDARIO" />
      <Association Name="DETALLE_PERSONAL_CALENDARIO_FALTAS" Member="FALTAS" ThisKey="IDCALENDARIO,CEDULA" OtherKey="IDCALENDARIO,CEDULA" Type="FALTAS" />
      <Association Name="CALENDARIO_DETALLE_PERSONAL_CALENDARIO" Member="CALENDARIO" ThisKey="IDCALENDARIO" OtherKey="IDCALENDARIO" Type="CALENDARIO" IsForeignKey="true" />
      <Association Name="PERSONAL_DETALLE_PERSONAL_CALENDARIO" Member="PERSONAL" ThisKey="CEDULA" OtherKey="CEDULA" Type="PERSONAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIASADICIONALES" Member="DIASADICIONALES">
    <Type Name="DIASADICIONALES">
      <Column Name="IDDIASADICIONALES" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="CALENDARIO_DIASADICIONALES" Member="CALENDARIO" ThisKey="IDCALENDARIO" OtherKey="IDCALENDARIO" Type="CALENDARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIASNOLABORABLES" Member="DIASNOLABORABLES">
    <Type Name="DIASNOLABORABLES">
      <Column Name="IDDIASNOLABORABLES" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="CALENDARIO_DIASNOLABORABLES" Member="CALENDARIO" ThisKey="IDCALENDARIO" OtherKey="IDCALENDARIO" Type="CALENDARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FALTAS" Member="FALTAS">
    <Type Name="FALTAS">
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DETALLE_PERSONAL_CALENDARIO_FALTAS" Member="DETALLE_PERSONAL_CALENDARIO" ThisKey="IDCALENDARIO,CEDULA" OtherKey="IDCALENDARIO,CEDULA" Type="DETALLE_PERSONAL_CALENDARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HUELLA" Member="HUELLA">
    <Type Name="HUELLA">
      <Column Name="IDHUELLA" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DATAHUELLA1" Type="System.Data.Linq.Binary" DbType="VarBinary(8000) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DATAHUELLA2" Type="System.Data.Linq.Binary" DbType="VarBinary(8000) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IMAGEN" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="PERSONAL_HUELLA" Member="PERSONAL" ThisKey="CEDULA" OtherKey="CEDULA" Type="PERSONAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IMPREVISTOS" Member="IMPREVISTOS">
    <Type Name="IMPREVISTOS">
      <Column Name="IDIMPREVISTO" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FECHAINICIO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAFINAL" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="IMPREVISTOS_DETALLE_IMPREVISTO_CALENDARIO" Member="DETALLE_IMPREVISTO_CALENDARIO" ThisKey="IDIMPREVISTO" OtherKey="IDIMPREVISTO" Type="DETALLE_IMPREVISTO_CALENDARIO" />
    </Type>
  </Table>
  <Table Name="dbo.MODULOS" Member="MODULOS">
    <Type Name="MODULOS">
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MOD_IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="MODULOS_MODULOS" Member="MODULOS2" ThisKey="IDMODULO" OtherKey="MOD_IDMODULO" Type="MODULOS" />
      <Association Name="MODULOS_RECURSOS" Member="RECURSOS" ThisKey="IDMODULO" OtherKey="IDMODULO" Type="RECURSOS" />
      <Association Name="MODULOS_MODULOS" Member="MODULOS1" ThisKey="MOD_IDMODULO" OtherKey="IDMODULO" Type="MODULOS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMISOS" Member="PERMISOS">
    <Type Name="PERMISOS">
      <Column Name="IDPERMISO" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDROL" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDRECURSO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LECTURA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ESCRITURA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ELIMINACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BUSQUEDA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RECURSOS_PERMISOS" Member="RECURSOS" ThisKey="IDRECURSO" OtherKey="IDRECURSO" Type="RECURSOS" IsForeignKey="true" />
      <Association Name="ROLES_PERMISOS" Member="ROLES" ThisKey="IDROL" OtherKey="IDROL" Type="ROLES" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERSONAL" Member="PERSONAL">
    <Type Name="PERSONAL">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="PERSONAL_DETALLE_PERSONAL_CALENDARIO" Member="DETALLE_PERSONAL_CALENDARIO" ThisKey="CEDULA" OtherKey="CEDULA" Type="DETALLE_PERSONAL_CALENDARIO" />
      <Association Name="PERSONAL_HUELLA" Member="HUELLA" ThisKey="CEDULA" OtherKey="CEDULA" Type="HUELLA" />
      <Association Name="PERSONAL_USUARIO" Member="USUARIO" ThisKey="CEDULA" OtherKey="CEDULA" Type="USUARIO" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.RECURSOS" Member="RECURSOS">
    <Type Name="RECURSOS">
      <Column Name="IDRECURSO" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URLRECURSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HABILITADOMENU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POSICIONMENU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="RECURSOS_PERMISOS" Member="PERMISOS" ThisKey="IDRECURSO" OtherKey="IDRECURSO" Type="PERMISOS" />
      <Association Name="MODULOS_RECURSOS" Member="MODULOS" ThisKey="IDMODULO" OtherKey="IDMODULO" Type="MODULOS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ROLES" Member="ROLES">
    <Type Name="ROLES">
      <Column Name="IDROL" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ROLES_PERMISOS" Member="PERMISOS" ThisKey="IDROL" OtherKey="IDROL" Type="PERMISOS" />
      <Association Name="ROLES_USUARIO" Member="USUARIO" ThisKey="IDROL" OtherKey="IDROL" Type="USUARIO" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIO" Member="USUARIO">
    <Type Name="USUARIO">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDROL" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CLAVE" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NICK" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="ROLES_USUARIO" Member="ROLES" ThisKey="IDROL" OtherKey="IDROL" Type="ROLES" IsForeignKey="true" />
      <Association Name="PERSONAL_USUARIO" Member="PERSONAL" ThisKey="CEDULA" OtherKey="CEDULA" Type="PERSONAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.insertarpersonalrapido" Method="insertarpersonalrapido">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ciudad" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_BuscarPersonalCedula" Method="pa_BuscarPersonalCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="pa_BuscarPersonalCedulaResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_EliminarPersonalCedula" Method="pa_EliminarPersonalCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_FiltrarPersonalValores" Method="pa_FiltrarPersonalValores">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="pa_FiltrarPersonalValoresResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_FiltrarRoles" Method="pa_FiltrarRoles">
    <Parameter Name="VALOR" Parameter="vALOR" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="pa_FiltrarRolesResult">
      <Column Name="IDROL" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_FiltrarUsuarios" Method="pa_FiltrarUsuarios">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="pa_FiltrarUsuariosResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ROL" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_USUARIO" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_getCedulaByNickClave" Method="pa_getCedulaByNickClave">
    <Parameter Name="NICK" Parameter="nICK" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CLAVE" Parameter="cLAVE" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="pa_getCedulaByNickClaveResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_GetUrlRecursoByNombreModulo" Method="pa_GetUrlRecursoByNombreModulo">
    <Parameter Name="NOMBREMODULO" Parameter="nOMBREMODULO" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="pa_GetUrlRecursoByNombreModuloResult">
      <Column Name="IDRECURSO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URLRECURSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HABILITADOMENU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POSICIONMENU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_InsertarModulo" Method="pa_InsertarModulo">
    <Parameter Name="IDMODULO" Parameter="iDMODULO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="MODIDMODULO" Parameter="mODIDMODULO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_InsertarPermiso" Method="pa_InsertarPermiso">
    <Parameter Name="idpermiso" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="idrol" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="idrecurso" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="lectura" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="escritura" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="eliminacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="modificacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="busqueda" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_InsertarRecurso" Method="pa_InsertarRecurso">
    <Parameter Name="idrecurso" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="idmodulo" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="urlrecurso" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="habilitadomenu" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="posicionmenu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_InsertarRol" Method="pa_InsertarRol">
    <Parameter Name="IDROL" Parameter="iDROL" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ESTADO" Parameter="eSTADO" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_InsertarUsuario" Method="pa_InsertarUsuario">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="IDROL" Parameter="iDROL" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NICK" Parameter="nICK" Type="System.String" DbType="VarChar(16)" />
    <Parameter Name="CLAVE" Parameter="cLAVE" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_Modificar_Permiso" Method="pa_Modificar_Permiso">
    <Parameter Name="idpermiso" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="idrol" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="idrecurso" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="lectura" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="escritura" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="eliminacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="modificacion" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="busqueda" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_ModificarPersonalCedula" Method="pa_ModificarPersonalCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Cargo" Parameter="cargo" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_ModificarUser" Method="pa_ModificarUser">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="idrol" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="nick" Type="System.String" DbType="VarChar(16)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.pa_ObtenerArbol" Method="pa_ObtenerArbol">
    <Parameter Name="nick" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(80)" />
    <ElementType Name="pa_ObtenerArbolResult">
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MOD_IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ObtenerArbolbyNombreRol" Method="pa_ObtenerArbolbyNombreRol">
    <Parameter Name="nombrerol" Type="System.String" DbType="VarChar(60)" />
    <ElementType Name="pa_ObtenerArbolbyNombreRolResult">
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MOD_IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_ObtenerPermisosByCedNombreMod" Method="pa_ObtenerPermisosByCedNombreMod">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nombremodulo" Type="System.String" DbType="VarChar(60)" />
    <ElementType Name="pa_ObtenerPermisosByCedNombreModResult">
      <Column Name="IDPERMISO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDROL" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDRECURSO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LECTURA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ESCRITURA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ELIMINACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BUSQUEDA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDRECURSO1" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ESTADO1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URLRECURSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HABILITADOMENU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POSICIONMENU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_Obtenerrecursosypermisosbynombrero" Method="pa_Obtenerrecursosypermisosbynombrero">
    <Parameter Name="nombrerol" Type="System.String" DbType="VarChar(60)" />
    <ElementType Name="pa_ObtenerrecursosypermisosbynombreroResult">
      <Column Name="IDPERMISO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDROL" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDRECURSO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LECTURA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ESCRITURA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ELIMINACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BUSQUEDA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDRECURSO1" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ESTADOREC" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="URLRECURSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HABILITADOMENU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POSICIONMENU" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pa_RegistrarPersonal" Method="pa_RegistrarPersonal">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Cargo" Parameter="cargo" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarPersonal" Method="sp_ActualizarPersonal">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Cargo" Parameter="cargo" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BuscarPersonalCedula" Method="sp_BuscarPersonalCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_BuscarPersonalCedulaResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Eliminar_Detalle_Imprevisto_Calendario" Method="sp_Eliminar_Detalle_Imprevisto_Calendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="IdImprevisto" Parameter="idImprevisto" Type="System.String" DbType="VarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarAsistenciaId" Method="sp_EliminarAsistenciaId">
    <Parameter Name="IDASISTENCIA" Parameter="iDASISTENCIA" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarCalendario" Method="sp_EliminarCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarDiasAdicionales" Method="sp_EliminarDiasAdicionales">
    <Parameter Name="IdDiaAdicional" Parameter="idDiaAdicional" Type="System.String" DbType="VarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarDiasNoLaborables" Method="sp_EliminarDiasNoLaborables">
    <Parameter Name="IdDiaNoLab" Parameter="idDiaNoLab" Type="System.String" DbType="VarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarFaltaId" Method="sp_EliminarFaltaId">
    <Parameter Name="IDFALTA" Parameter="iDFALTA" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarHuellaIdHuella" Method="sp_EliminarHuellaIdHuella">
    <Parameter Name="idHuella" Type="System.String" DbType="VarChar(8)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarImprevistoId" Method="sp_EliminarImprevistoId">
    <Parameter Name="IDIMPREVISTO" Parameter="iDIMPREVISTO" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarPersonalCedula" Method="sp_EliminarPersonalCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarRol" Method="sp_EliminarRol">
    <Parameter Name="idrol" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarUser" Method="sp_EliminarUser">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_FiltrarAsistenciaDia" Method="sp_FiltrarAsistenciaDia">
    <Parameter Name="IDCALENDARIO" Parameter="iDCALENDARIO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="valor" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_FiltrarAsistenciaDiaResult">
      <Column Name="IDASISTENCIA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_FiltrarAsistenciaMes" Method="sp_FiltrarAsistenciaMes">
    <Parameter Name="IDCALENDARIO" Parameter="iDCALENDARIO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="valor" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_FiltrarAsistenciaMesResult">
      <Column Name="IDASISTENCIA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_FiltrarAsistenciaRango" Method="sp_FiltrarAsistenciaRango">
    <Parameter Name="IDCALENDARIO" Parameter="iDCALENDARIO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="fechainicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fechafin" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_FiltrarAsistenciaRangoResult">
      <Column Name="IDASISTENCIA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_FiltrarFaltaDia" Method="sp_FiltrarFaltaDia">
    <Parameter Name="IDCALENDARIO" Parameter="iDCALENDARIO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="valor" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_FiltrarFaltaDiaResult">
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_FiltrarFaltaMes" Method="sp_FiltrarFaltaMes">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="valor" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_FiltrarFaltaMesResult">
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_FiltrarFaltaRango" Method="sp_FiltrarFaltaRango">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="fechainicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fechafin" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_FiltrarFaltaRangoResult">
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_FiltrarPersonalValores" Method="sp_FiltrarPersonalValores">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="sp_FiltrarPersonalValoresResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarCalendario" Method="sp_ListarCalendario">
    <ElementType Name="sp_ListarCalendarioResult">
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FECHAINICIO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAFIN" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarDetallePersonalCalendario" Method="sp_ListarDetallePersonalCalendario">
    <Parameter Name="cedula" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_ListarDetallePersonalCalendarioResult">
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarDiaAdicional" Method="sp_ListarDiaAdicional">
    <ElementType Name="sp_ListarDiaAdicionalResult">
      <Column Name="IDDIASADICIONALES" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarDiaNoLaborables" Method="sp_ListarDiaNoLaborables">
    <ElementType Name="sp_ListarDiaNoLaborablesResult">
      <Column Name="IDDIASNOLABORABLES" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ModificarCalendario" Method="sp_ModificarCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarDetallePersonalCalendario" Method="sp_ModificarDetallePersonalCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarDiaAdicional" Method="sp_ModificarDiaAdicional">
    <Parameter Name="IdDiaAdicional" Parameter="idDiaAdicional" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarDiaNoLaborable" Method="sp_ModificarDiaNoLaborable">
    <Parameter Name="IdDiaNoLAb" Parameter="idDiaNoLAb" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarFaltaJustificacion" Method="sp_ModificarFaltaJustificacion">
    <Parameter Name="IDFALTA" Parameter="iDFALTA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="JUSTIFICACION" Parameter="jUSTIFICACION" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarHuellaIdHuella" Method="sp_ModificarHuellaIdHuella">
    <Parameter Name="IdHuella" Parameter="idHuella" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="DataHuella1" Parameter="dataHuella1" Type="System.Data.Linq.Binary" DbType="Binary(1)" />
    <Parameter Name="DataHuella2" Parameter="dataHuella2" Type="System.Data.Linq.Binary" DbType="Binary(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarImprevistoId" Method="sp_ModificarImprevistoId">
    <Parameter Name="IDIMPREVISTO" Parameter="iDIMPREVISTO" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="FECHAINICIO" Parameter="fECHAINICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FECHAFINAL" Parameter="fECHAFINAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarPersonalSinFoto" Method="sp_ModificarPersonalSinFoto">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DataFoto" Parameter="dataFoto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarRol" Method="sp_ModificarRol">
    <Parameter Name="idrol" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Obtener_Personas_Imprevisto" Method="sp_Obtener_Personas_Imprevisto">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="IdImprevisto" Parameter="idImprevisto" Type="System.String" DbType="VarChar(6)" />
    <ElementType Name="sp_Obtener_Personas_ImprevistoResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporCalendario" Method="sp_PersonalporCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="sp_PersonalporCalendarioResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DATAFOTO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporFaltaMes" Method="sp_PersonalporFaltaMes">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FechaMes" Parameter="fechaMes" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_PersonalporFaltaMesResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL_FALTAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JUSTIFICADAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NO_JUSTIFICADAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporFaltaRango" Method="sp_PersonalporFaltaRango">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_PersonalporFaltaRangoResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL_FALTAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JUSTIFICADAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NO_JUSTIFICADAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_RegistrarAsistencia" Method="sp_RegistrarAsistencia">
    <Parameter Name="IDASISTENCIA" Parameter="iDASISTENCIA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="IDCALENDARIO" Parameter="iDCALENDARIO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FECHAHORAENTRADA" Parameter="fECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FECHAHORASALIDA" Parameter="fECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarCalendario" Method="sp_RegistrarCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarDiaAdicional" Method="sp_RegistrarDiaAdicional">
    <Parameter Name="IdDiaAdicional" Parameter="idDiaAdicional" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarDiaNoLab" Method="sp_RegistrarDiaNoLab">
    <Parameter Name="IdDiaNoLab" Parameter="idDiaNoLab" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarFalta" Method="sp_RegistrarFalta">
    <Parameter Name="IDFALTA" Parameter="iDFALTA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="IDCALENDARIO" Parameter="iDCALENDARIO" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FECHA" Parameter="fECHA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="JUSTIFICACION" Parameter="jUSTIFICACION" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarHuella" Method="sp_RegistrarHuella">
    <Parameter Name="IdHuella" Parameter="idHuella" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DataHuella1" Parameter="dataHuella1" Type="System.Data.Linq.Binary" DbType="Binary(1)" />
    <Parameter Name="DataHuella2" Parameter="dataHuella2" Type="System.Data.Linq.Binary" DbType="Binary(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarImprevistos" Method="sp_RegistrarImprevistos">
    <Parameter Name="IDIMPREVISTO" Parameter="iDIMPREVISTO" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="FECHAINICIO" Parameter="fECHAINICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FECHAFINAL" Parameter="fECHAFINAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarPersonal" Method="sp_RegistrarPersonal">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Cargo" Parameter="cargo" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarPersonalCalendario" Method="sp_RegistrarPersonalCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.vaciarseguridad" Method="vaciarseguridad">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ModificarPersonalCedula" Method="sp_ModificarPersonalCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Cargo" Parameter="cargo" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipo" Parameter="tipo" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarAsistenciainterfFalta" Method="sp_EliminarAsistenciainterfFalta">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ImprevistosporCalendario" Method="sp_ImprevistosporCalendario">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="sp_ImprevistosporCalendarioResult">
      <Column Name="IDIMPREVISTO" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HORA_ENTRADA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HORA_SALIDA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ContarImprevisto" Method="sp_ContarImprevisto">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="sp_ContarImprevistoResult">
      <Column Name="IDIMPREVISTO" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="FECHAINICIO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAFINAL" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReportePersonal" Method="sp_ReportePersonal">
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="sp_ReportePersonalResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ObtenerArbol" Method="sp_ObtenerArbol">
    <Parameter Name="nick" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="clave" Type="System.String" DbType="VarChar(80)" />
    <ElementType Name="sp_ObtenerArbolResult">
      <Column Name="IDMODULO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MOD_IDMODULO" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ModificarAsistenciaFechaFinal" Method="sp_ModificarAsistenciaFechaFinal">
    <Parameter Name="IdAsistencia" Parameter="idAsistencia" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_FiltrarPersonalValor" Method="sp_FiltrarPersonalValor">
    <Parameter Name="valor" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="sp_FiltrarPersonalValorResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CARGO" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TITULO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CIUDAD" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarHuellaCedula" Method="sp_ListarHuellaCedula">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_ListarHuellaCedulaResult">
      <Column Name="IDHUELLA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DATAHUELLA1" Type="System.Data.Linq.Binary" DbType="VarBinary(8000) NOT NULL" CanBeNull="false" />
      <Column Name="DATAHUELLA2" Type="System.Data.Linq.Binary" DbType="VarBinary(8000) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IMAGEN" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporAsistenciaRango" Method="sp_PersonalporAsistenciaRango">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FechaInicio" Parameter="fechaInicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaFin" Parameter="fechaFin" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_PersonalporAsistenciaRangoResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL_ASISTENCIAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_HORAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporAsistenciaMes" Method="sp_PersonalporAsistenciaMes">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="FechaMes" Parameter="fechaMes" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_PersonalporAsistenciaMesResult">
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL_ASISTENCIAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_HORAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporAsistenciaDia" Method="sp_PersonalporAsistenciaDia">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_PersonalporAsistenciaDiaResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="HoraEntrada" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="HoraSalida" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Tiempo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHAHORAENTRADA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHAHORASALIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="IDASISTENCIA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PersonalporFaltaDia" Method="sp_PersonalporFaltaDia">
    <Parameter Name="IdCalendario" Parameter="idCalendario" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_PersonalporFaltaDiaResult">
      <Column Name="IDFALTA" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JUSTIFICACION" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDCALENDARIO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CEDULA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>